version: "3"
services:
  moe-bangumi:
    image: birdgg/moe-bangumi:latest
    container_name: moe-bangumi
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - PORT=7789
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/moe-bangumi/config:/config
      - /volume1/Media:/Media # 番剧挂载路径，两侧须保持一致
    restart: always
    network_mode: host
  qBittorrent:
    image: superng6/qbittorrent:latest
    container_name: qBittorrent
    environment:
      - PUID=0
      - PGID=0
      - WEBUI_PORT=8080 
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/qBittorrent/config:/config
      - /volume1/downloads:/downloads
      - /volume1/Media:/Media # 番剧挂载路径，两侧须保持一致
    restart: always
    network_mode: host